### ISSUE TITLE
Discussion/Question: Roadmap for end-to-end tests ref https://apitest.dev/docs/config#networking

### ISSUE THREAD

**Issue by jitendra-1217** [steinfletcher/apitest#112]
Referring https://apitest.dev/docs/config#networking
> If you want to generate HTTP requests against a running application you should enable networking. This approach can be useful for performing end-to-end tests.

The end-to-end test support is mentioned in this particular section, but then the rest of the documentations are a bit disconnected on this(end-to-end) pov. E.g. mocks, and reports will not work with tests written with the EnableNetworking option- hoping this is the right understanding(?).

Is there any roadmap/to-do list to further enhance support for end-to-end tests? :) I would want to further discuss if there is interest.

**Comment by steinfletcher** [comment]
Hi @jitendra-1217. 

I've written a couple of tests using `EnableNetworking`, mostly to smoke test an application after it's deployed, but generally I tend to avoid writing a lot of these kind of tests because they are expensive to maintain and are not repeatable.

If there are missing features or anything you find isn't working, I'd be keen to get feedback so we can resolve any issues you have.

In terms of setting up api tests and writing assertions, there isn't much difference with `EnableNetworking` enabled or disabled.

Cheers

**Comment by jitendra-1217** [comment]
@steinfletcher : I had a scenario where was planning to use end-to-end tests for more than just smoke tests. I will post separate issues for enhancements around end-to-end tests, when I am able to detail them.

Thanks for your reply. Closing this thread for now.
