### ISSUE TITLE
Adding custom context to Request

### ISSUE THREAD

**Issue by emmanuelay** [steinfletcher/apitest#126]
**Is your feature request related to a problem? Please describe.**
I rely on being able to gracefully stop calls to logic & persistence when requests are cancelled by passing down the context to my requests. 

For example I have an endpoint that performs an autocompletion operation that is costly. Clients do cancel their requests when the user has modified the search terms. When the cancelled context is detected in the call, it bubbles up to the handler and should yield an empty HTTP 204 response to the clients, rather than a HTTP 400 or HTTP 500. So in my handlers I have code that does this:

```
data, err := h.service.Query(ctx, req)
if err != nil {
     if errors.Is(err, context.Canceled) {
         // Return a HTTP 204
     }
     // Return either 4xx or 500
}
```

**Describe the solution you'd like**
I would like to be able to do something like:
```
// The context could have a short timeout or be cancelled, just to verify certain behavior
ctx, cancel := context.WithTimeout(context.Background(), time.Duration(time.Millisecond*10))
defer cancel()

apitest.New().
    Handler(router).
    Get("/trips").
    QueryParams(test.params).
    WithContext(ctx). // <-- a convenient way of passing a context to the requests httpClient
    Expect(t).
    Status(test.expectedStatus)
```

**Describe alternatives you've considered**
It is possible to do this today in apitest by using an interceptor or a custom http client. But the suggested method makes it a lot more convenient.

**Comment by steinfletcher** [comment]
Hey @emmanuelay. 

I'd be happy to take a PR for this - I don't think I'll get to it anytime soon because of other priorities.

If you want to have a go at it, I think you can just pick up the context in the `buildRequest` method.  Should be fairly simple https://github.com/steinfletcher/apitest/blob/76030d3088d55634fdbb95514654184ea43c6882/apitest.go#L953

Note there's also the `HttpRequest` method where you can pass a request in, which I think is simpler than the interceptor or custom client approach.

Cheers

**Comment by emmanuelay** [comment]
Sure, I'll have a stab at it. Thanks for the advice!

**Comment by emmanuelay** [comment]
Anything else you'd like me to add @steinfletcher ?
